### ISSUE TITLE
Update README with better instructions

### ISSUE THREAD

**Issue by ZacheryPD** [NCSU-CSC510-Group-E/WolfTutor#1]
I ran into major issues when trying to get things set up.  Need to update with closer step-by-step instrucitons

**Comment by ZacheryPD** [comment]
I have fixed the major issues I had before, but now I've found more

1. There is no mention of the required DB initialization
2. There is no mention of the required bot permissions (They are non standard)

Both of the above should also be added.

**Comment by mgmetro4** [comment]
Fixed.
