### ISSUE TITLE
Create a way to migrate data into heroku database

### ISSUE THREAD

**Issue by ZacheryPD** [NCSU-CSC510-Group-E/WolfTutor#26]

**Comment by mgmetro4** [comment]
## **To export via command line on local machine:**
`mongodump  -d dbName -o outPath/`
use your own personal zip program for easy emailing - mongo's archive files are kind of buggy
Should create an outPath/dbName hierarchy
outPath is dump/dbname by default (current working directory)

## **To import via command line on local machine:**
`mongorestore -d dbName inputPath/inputDbName`

## **To import to Heroku:**
mlab offers me the complete command line instructions to run to import and export into heroku. The above methods are for binary files and is recommended for accuracy.
